---
- hosts: localhost
  connection: local

  vars_prompt:

  - name: esteundar
    prompt: "Esti un BENEFICIAR al Asociatiei unPi pentru Scolari?"
    private: no
    default: "DA"

  - name: hashedcode
    prompt: "Care este PAROLA pe care ai primit-o de la Asociatia unPi?"
    encrypt: "scrypt"
    salt: "@unPi"
    private: no
    confirm: yes

  tasks:

   # este beneficiar daca a primit unPi in dar
   - set_fact: beneficiar=true verificat=false
     when: esteundar | upper == "DA" or esteundar | bool

   # nu este beneficiar daca nu a primit unPi in dar
   - set_fact: beneficiar=false verificat=false
     when: esteundar | upper != "DA" and not esteundar | bool

   - name: "Pregatesc un director pentru configuratia unPi"
     file:
       dest: "/root/.unpi"
       mode: u=rwx,g=,o=
       state: directory
     become: yes

   - name: "Salvez raspunsul la intrebarea daca esti BENEFICIAR"
     copy:
       dest: /root/.unpi/esteundar
       mode: u=rw,g=,o=
       content: "{{ esteundar }}"
     become: yes

   - name: "Salvez raspunsul la intrebarea despre PAROLA ta unPi"
     copy:
       dest: /root/.unpi/hashedcode
       mode: u=rw,g=,o=
       content: "{{ hashedcode }}"
     become: yes
     
   - name: "Instalam mediul educational GCompris"
     apt:
       name: gcompris
     become: yes

   - name: "Instalam limbajele de programare Scratch 3 si Golang"
     apt:
       name: git,scratch3,golang
     become: yes

   - name: "Stergem versiunile vechi (v1, v2) ale programului Scrach"
     apt:
       name: scratch,scratch2
       state: absent
     become: yes
     when: beneficiar

   - name: "Instalam cele mai noi aplicatii pentru calculatorul tau"
     apt:
       upgrade: full
       update_cache: yes
     become: yes
