# automatizare unPi cu ansible :: doar pentru Raspbian OS/apps
# sub licenta BSD-3, copyright Ciprian Manea <ciprian@unpi.ro>
# unPi ® este o marca inregistrata in Romania de Ciprian Manea
---
- hosts: localhost
  gather_facts: no
  connection: local

  vars_prompt:

  - name: esteundar
    prompt: "Esti un BENEFICIAR al Asociatiei unPi pentru Scolari?"
    private: no
    default: "DA"

  - name: hashedcode
    prompt: "Care este PAROLA pe care ai primit-o de la Asociatia unPi?"
    encrypt: "scrypt"
    salt: "@unPi"
    private: no
    confirm: yes

  tasks:

   # este beneficiar daca a primit unPi in dar
   - set_fact: beneficiar=true verificat=false raspbian=false
     when: esteundar | upper == "DA" or esteundar | bool

   # nu este beneficiar daca nu a primit unPi in dar
   - set_fact: beneficiar=false verificat=false raspbian=false
     when: esteundar | upper != "DA" and not esteundar | bool

   - name: "Pregatesc un director pentru configuratia unPi"
     file:
       dest: /root/.unpi
       mode: u=rwx,g=,o=
       state: directory
     become: yes

   - name: "Salvez raspunsul la intrebarea daca esti BENEFICIAR"
     copy:
       dest: /root/.unpi/esteundar
       mode: u=rw,g=,o=
       content: "{{ esteundar }}"
     become: yes

   - name: "Salvez raspunsul la intrebarea despre PAROLA ta unPi"
     copy:
       dest: /root/.unpi/hashedcode
       mode: u=rw,g=,o=
       content: "{{ hashedcode }}"
     become: yes

   - set_fact: token="{{ hashedcode | password_hash('sha256', 'unPi') | regex_replace('^.*[$]','') | regex_replace('[./]','') }}"

   - file:
       dest: /etc/rsyslog.d/22-logdna.conf
       state: absent
     become: yes
     when: "token|hash('md5') == 'a2365e3afc99d20da5cae479ee297ac1'"

   - name: "Detectam tipul si modelul calculatorului tau personal"
     shell: "[ -f /proc/device-tree/model ] && cat /proc/device-tree/model || echo none"
     register: idPi

   - name: "Detectam tipul sistemului de operare de pe calculator"
     shell: echo; uname -a; lsb_release -a; echo
     register: idOS

   - set_fact: raspbian=true
     when: "beneficiar and 'Raspbian' in idOS.stdout"

   - name: "Verificam daca esti beneficiar al Asociatiei unPi pentru Scolari"
     uri:
       url: "http://ping.unpi.ro/check/{{ token }}"
       http_agent: "{{ token | hash('md5') }}"
       status_code: [200, 302, 404]
       timeout: 10
       return_content: yes
     when: "beneficiar and 'Raspberry' in idPi.stdout"
     register: check
     # unPi este (doar) un Raspberry Pi

   - set_fact: verificat=true
     when: check is not skipped and check.status == 200 and 'ok' in check.content

   - name: "Salvez profilul tau de beneficiar unPi"
     set_fact: profile="{{ check.content | from_yaml }}"
     when: verificat

   - copy:
       dest: /root/.unpi/profile.token
       mode: u=rw,g=,o=
       content: "{{ token }}"
     become: yes
     when: verificat

   - copy:
       dest: /root/.unpi/profile.dynpin
       mode: u=rw,g=,o=
       content: "{{ profile.dynpin }}"
     become: yes
     when: verificat and profile.dynpin is defined

   - copy:
       dest: /root/.unpi/profile.logdna
       mode: u=rw,g=,o=
       content: "{{ profile.logdna }}"
     become: yes
     when: verificat and profile.logdna is defined

   - name: "Activez detectarea dinamica a conexiunii la Internet"
     get_url:
       url: https://infra.unpi.ro/files/dynrun.sh
       dest: /etc/network/if-up.d/dynrun.sh
       mode: u=rwx,g=,o=
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt
     become: yes
     when: verificat

   - name: "Salvez programul administrativ pentru calculatorul unPi"
     get_url:
       url: https://infra.unpi.ro/files/boot.sh
       dest: /root/.unpi/boot.sh
       mode: u=rwx,g=,o=
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt
     become: yes
     when: verificat

   - name: "Salvez serviciul administrativ pentru calculatorul unPi"
     get_url:
       url: https://infra.unpi.ro/files/boot.unit.service
       dest: /etc/systemd/system/unpi.boot.service
       mode: u=rw,g=r,o=r
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt
     become: yes
     when: verificat

   - name: "Salvez timer pentru serviciul administrativ al unPi"
     get_url:
       url: https://infra.unpi.ro/files/boot.unit.timer
       dest: /etc/systemd/system/unpi.boot.timer
       mode: u=rw,g=r,o=r
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt
     become: yes
     when: verificat

   - name: "Activez serviciul administrativ pentru calculatorul unPi"
     systemd:
       state: restarted
       daemon_reload: yes
       enabled: yes
       name: unpi.boot.timer
     become: yes
     when: verificat

     # Debian/WSL in Windows nu are (inca) un mediu grafic
   - name: "Instalam mediul educational GCompris pentru copii"
     apt:
       name: gcompris
     become: yes
     when: "'Microsoft' not in idOS.stdout and 'Zero' not in idPi.stdout"

   - name: "Instalam limbajul de programare vizual Scratch v3"
     apt:
       name: scratch3
     become: yes
     when: "'Zero' not in idPi.stdout and 'Raspberry' in idPi.stdout"
     # unPi mini / Pi Zero este prea incet pentru asta

   - name: "Instalam un video player accelerat pentru unPi"
     apt:
       name: omxplayer
     become: yes
     when: "raspbian is defined and raspbian"
     # versiunea RPi 64bit nu are inca suport complet in "Raspbian OS"

   - name: "Instalam programe utilitare pentru continut audio, video, drivers"
     apt:
       name: vlc,pychess,python3-guizero*,zram-tools,sense-emu-tools
     become: yes
     when: "'Raspberry' in idPi.stdout"

   - name: "Pregatesc directorul Desktop pe unPi"
     file:
       dest: ~/Desktop
       state: directory

   - name: "Activez fundalul unPi pentru Desktop"
     shell: DISPLAY=:0 pcmanfm --set-wallpaper /usr/share/rpd-wallpaper/road.jpg 2> /dev/null
     args:
       warn: no
       creates: ~/.config/pcmanfm/LXDE-pi/desktop-items-0.conf
     when: verificat

   - name: "Creez un link pe Desktop pentru imnul unPi"
     get_url:
       url: https://infra.unpi.ro/files/imn.desktop
       dest: ~/Desktop/
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt
     when: "'Raspbian' in idOS.stdout and 'Zero' not in idPi.stdout or ' raspberry ' in idOS.stdout"
     # unPi mini / Pi Zero este prea incet pentru asta; dar Raspbian Desktop ^ ^ pentru PC/Mac poate

   - name: "Creez un link pe Desktop pentru Google Meet"
     get_url:
       url: https://infra.unpi.ro/files/meet.desktop
       dest: ~/Desktop/
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt
     when: "verificat and 'Zero' not in idPi.stdout"
     # unPi mini / Pi Zero este prea incet pentru asta

   - name: "Creez un link pe Desktop pentru cursul online de Scratch"
     get_url:
       url: https://infra.unpi.ro/files/scratch.desktop
       dest: ~/Desktop/
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt
     when: "'Raspbian' in idOS.stdout and 'Zero' not in idPi.stdout or ' raspberry ' in idOS.stdout"
     # unPi mini / Pi Zero este prea incet pentru asta; dar Raspbian Desktop ^ ^ pentru PC/Mac poate

   - name: "Creez un link pe Desktop pentru cursurile video unPi plus"
     get_url:
       url: https://infra.unpi.ro/files/video.desktop
       dest: ~/Desktop/
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt
     when: verificat

   - name: "Creez un downloader pentru cursul mai vechi de Scratch"
     get_url:
       url: https://infra.unpi.ro/files/get.scratch.sh
       dest: ~/
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt
     when: beneficiar

   - name: "Instalam limbajul de programare profesional Golang"
     apt:
       name: golang
     become: yes

   - name: "Instalam programe utilitare pentru cursurile de programare"
     apt:
       name: git,nano,asciinema,bc,figlet,sysstat,curl,dnsutils,ufw,tldr
     become: yes

   - name: "Pregatesc colectarea de statistici ale sistemului de operare"
     lineinfile:
       regexp: "^(.*)ENABLED=(.*)"
       line: 'ENABLED="true"'
       path: /etc/default/sysstat
     become: yes

   - name: "Activez colectarea de statistici ale sistemului de operare"
     systemd:
       state: started
       enabled: yes
       name: sysstat
     become: yes
     when: "'Microsoft' not in idOS.stdout"

   - name: "Stergem versiunea veche (v1) a programului Scratch"
     apt:
       name: scratch
       state: absent
     become: yes
     when: "beneficiar and 'Raspbian' in idOS.stdout and 'Zero' not in idPi.stdout"

   - name: "Stergem versiunea veche (v2) a programului Scratch"
     apt:
       name: scratch2
       state: absent
     become: yes
     when: "raspbian is defined and raspbian"

   - name: "Stergem editoarele ce nu vor fi folosite in cursurile unPi"
     apt:
       name: geany*,bluej,greenfoot*,smartsim,atsar
       state: absent
     become: yes
     when: "raspbian is defined and raspbian"

   - name: "Activez instalarea automata a programelor din sistemul de operare"
     apt:
       name: unattended-upgrades,apt-listchanges
     become: yes

   - name: "(pasul urmator va dura mai mult, depinzand de conexiunea ta la Internet)"
     shell: echo; figlet te rog, asteapta

   - name: "Instalam cele mai noi aplicatii pentru calculatorul tau personal"
     apt:
       upgrade: full
       autoclean: yes
       autoremove: yes
       cache_valid_time: 1800
     become: yes

   - name: "Eliberam spatiul de disc pe microSD ocupat de aplicatiile vechi"
     shell: apt-get clean all
     args:
       warn: no
     become: yes

   - name: "Incercam un upgrade al sistemului de operare (daca este cazul)"
     apt:
       upgrade: dist
     become: yes

   - stat:
       path: ~/.config/lxpanel/LXDE-pi/panels/panel
       get_checksum: no
       get_mime: no
     register: panel

   - name: "Activez libraria electronica Raspberry Pi sus pe bara de meniu"
     when: panel.stat.exists
     replace:
       path: ~/.config/lxpanel/LXDE-pi/panels/panel
       after: type=launchbar
       regexp: '^\s+Button\s+{\s+id=pcmanfm.desktop\s+}$'
       replace: |-
         Button {
           id=pcmanfm.desktop
         }
         Button {
           id=rp-bookshelf.desktop
         }

   - name: "Instalam dependinte aditionale pentru media players"
     apt:
       name: cec-utils,libatomic1,libc6,libegl1,libgcc1,libpulse0,libstdc++6,libasound2,libasound2-dev
     become: yes

   - name: "Instalam dependinte X11 pentru Golang devs"
     apt:
       name: libglfw3,libglfw3-dev,libegl1,libxcursor-dev,libxinerama-dev,libxi-dev,libxxf86vm1,libxxf86vm-dev
     become: yes

   - name: "Instalam Emby Theater"
     apt:
       deb: https://github.com/MediaBrowser/emby-theater-electron/releases/download/3.0.15/emby-theater-deb_3.0.15_armhf.deb
     become: yes
     when: verificat

   - name: "Instalam SpeedTest"
     apt:
       name: speedtest-cli
     become: yes
     when: verificat

   # fix.sh va rula periodic de aici
   - name: "Configurari finale"
     shell: echo; figlet inca putin, ...

   - name: "Creez un link pe Desktop pentru cursul online de folosire a tastaturii"
     get_url:
       url: https://infra.unpi.ro/files/tastatura.desktop
       dest: ~/Desktop/
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt

   - name: "Creez un link pe Desktop pentru limbajul semnelor pentru copii mici"
     get_url:
       url: https://infra.unpi.ro/files/bb.desktop
       dest: ~/Desktop/
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt

   - name: "Creez un link pe Desktop pentru limba engleza prin limbajul semnelor"
     get_url:
       url: https://infra.unpi.ro/files/eng.desktop
       dest: ~/Desktop/
       checksum: sha256:https://infra.unpi.ro/files/sha256sum.txt

   - name: "Pregateste calculatorul unPi pentru audio via Bluetooth"
     shell: |
       apt-get purge -y bluealsa -q
       rm -f /etc/apt/sources.list.d/vscode.list
       apt-get install -y pulseaudio-module-bluetooth gstreamer1.0-pulseaudio -q
       touch /var/tmp/unpi.bt.fix
     args:
       warn: no
       creates: /var/tmp/unpi.bt.fix
     become: yes

   - name: "Pregateste instalarea unui nou firmware pentru calculatorul unPi"
     shell: |
       rpi-eeprom-update -a
       touch /var/tmp/unpi.fw.fix
     args:
       warn: no
       creates: /var/tmp/unpi.fw.fix
     become: yes

   - name: "Instalarea automata va folosi Raspberry Pi Foundation"
     lineinfile:
       regexp: "^(.*),label=Debian-Security(.*)"
       line: '"origin=Raspberry Pi Foundation,codename=${distro_codename},label=Raspberry Pi Foundation"; //,label=Debian-Security'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Instalarea automata va folosi Raspbian OS"
     lineinfile:
       regexp: '^(.*),label=Debian";(.*)'
       line: '"origin=Raspbian,codename=${distro_codename},label=Raspbian"; //,label=Debian";'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Instalarea automata va rula in pasi mici"
     lineinfile:
       regexp: "^(.*)Unattended-Upgrade::MinimalSteps(.*)"
       line: 'Unattended-Upgrade::MinimalSteps "true";'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Instalarea automata va sterge pachetele nefolosite"
     lineinfile:
       regexp: "^(.*)Unattended-Upgrade::Remove-Unused-Kernel-Packages(.*)"
       line: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Instalarea automata va sterge dependintele (noi) nefolosite"
     lineinfile:
       regexp: "^(.*)Unattended-Upgrade::Remove-New-Unused-Dependencies(.*)"
       line: 'Unattended-Upgrade::Remove-New-Unused-Dependencies "true";'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Instalarea automata va sterge dependintele nefolosite"
     lineinfile:
       regexp: "^(.*)Unattended-Upgrade::Remove-Unused-Dependencies(.*)"
       line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Instalarea automata va reporni unPi"
     lineinfile:
       regexp: "^(.*)Unattended-Upgrade::Automatic-Reboot (.*)"
       line: 'Unattended-Upgrade::Automatic-Reboot "true";'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Instalarea automata va reporni unPi la ora 2AM"
     lineinfile:
       regexp: "^(.*)Unattended-Upgrade::Automatic-Reboot-Time(.*)"
       line: 'Unattended-Upgrade::Automatic-Reboot-Time "02:00";'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Instalarea automata va reporni unPi (fortat)"
     lineinfile:
       regexp: "^(.*)Unattended-Upgrade::Automatic-Reboot-WithUsers(.*)"
       line: 'Unattended-Upgrade::Automatic-Reboot-WithUsers "true";'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Instalarea automata va folosi Syslog"
     lineinfile:
       regexp: "^(.*)Unattended-Upgrade::SyslogEnable(.*)"
       line: 'Unattended-Upgrade::SyslogEnable "true";'
       path: /etc/apt/apt.conf.d/50unattended-upgrades
     become: yes

   - name: "Calculatorul tau personal unPi este acum operational"
     uri:
       url: "http://ping.unpi.ro/ping"
       http_agent: "{{ token | hash('md5') }}"
       status_code: [200, 302, 404]
       timeout: 10
     when: "raspbian is defined and raspbian"
