# automatizare unPi cu ansible :: doar pentru Raspbian OS/apps
# sub licenta BSD-3, copyright Ciprian Manea <ciprian@unpi.ro>
# unPi ® este o marca inregistrata in Romania de Ciprian Manea
---
- hosts: localhost
  connection: local

  vars_prompt:

  - name: esteundar
    prompt: "Esti un BENEFICIAR al Asociatiei unPi pentru Scolari?"
    private: no
    default: "DA"

  - name: hashedcode
    prompt: "Care este PAROLA pe care ai primit-o de la Asociatia unPi?"
    encrypt: "scrypt"
    salt: "@unPi"
    private: no
    confirm: yes

  tasks:

   # este beneficiar daca a primit unPi in dar
   - set_fact: beneficiar=true verificat=false
     when: esteundar | upper == "DA" or esteundar | bool

   # nu este beneficiar daca nu a primit unPi in dar
   - set_fact: beneficiar=false verificat=false
     when: esteundar | upper != "DA" and not esteundar | bool

   - name: "Pregatesc un director pentru configuratia unPi"
     file:
       dest: "/root/.unpi"
       mode: u=rwx,g=,o=
       state: directory
     become: yes

   - name: "Salvez raspunsul la intrebarea daca esti BENEFICIAR"
     copy:
       dest: /root/.unpi/esteundar
       mode: u=rw,g=,o=
       content: "{{ esteundar }}"
     become: yes

   - name: "Salvez raspunsul la intrebarea despre PAROLA ta unPi"
     copy:
       dest: /root/.unpi/hashedcode
       mode: u=rw,g=,o=
       content: "{{ hashedcode }}"
     become: yes
     
   - name: "Instalam mediul educational GCompris"
     apt:
       name: gcompris
     become: yes

   - name: "Instalam limbajul de programare vizual Scratch v3"
     apt:
       name: scratch3,omxplayer
     become: yes
     when: ansible_lsb.id == "Raspbian"

   - name: "Instalam limbajul de programare profesional Golang"
     apt:
       name: golang
     become: yes

   - name: "Instalam programe utilitare pentru cursul de programare"
     apt:
       name: git,nano,asciinema,vlc,bc,figlet
     become: yes

   - name: "Stergem versiunile vechi (v1, v2) ale programului Scratch"
     apt:
       name: scratch,scratch2
       state: absent
     become: yes
     when: beneficiar and ansible_lsb.id == "Raspbian"

   - name: "Stergem editoarele ce nu vor fi folosite in cursurile unPi"
     apt:
       name: geany*,bluej,greenfoot*,smartsim
       state: absent
     become: yes
     when: beneficiar and ansible_lsb.id == "Raspbian"

   - name: "(pasul urmator va dura mai mult, depinzand de conexiunea ta la Internet)"
     shell: echo; figlet te rog, asteapta

   - name: "Instalam cele mai noi aplicatii pentru calculatorul tau personal"
     apt:
       upgrade: full
       update_cache: yes
     become: yes
