# automatizare unPi cu ansible :: doar pentru Raspbian OS/apps
# sub licenta BSD-3, copyright Ciprian Manea <ciprian@unpi.ro>
# unPi ® este o marca inregistrata in Romania de Ciprian Manea
---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:

    - name: "Pregatesc directorul Desktop pe unPi"
      file:
        dest: ~/Desktop
        state: directory

    - name: "(pasul urmator va dura mai mult, depinzand de conexiunea ta la Internet)"
      shell: echo; figlet te rog, asteapta

    - name: "Aducem programul de instalare pentru Blinkt!"
      uri:
        url: https://get.pimoroni.com/blinkt
        timeout: 20
        return_content: yes
      register: blinkt

    - copy:
        dest: /tmp/blinkt
        mode: u=rwx,g=,o=
        content: "{{ blinkt.content }}"
      when: blinkt.content is defined

    - name: "Configuram unPi mini pentru Pimoroni Blinkt!"
      shell: /tmp/blinkt -y
      when: blinkt.content is defined

    - name: "Creez un program exemplu pentru un Blinkt colorat"
      file:
        src: ~/Pimoroni/blinkt/examples/random_blink_colours.py
        dest: ~/blink
        state: hard
        force: yes
