# automatizare unPi cu ansible :: doar pentru Raspbian OS/apps
# sub licenta BSD-3, copyright Ciprian Manea <ciprian@unpi.ro>
# unPi ® este o marca inregistrata in Romania de Ciprian Manea
---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  
    - name: "Instalam dependintele necesare pentru unPi mini"
      apt:
        name: python-pip,python3-pip,raspi-gpio,python-rpi.gpio,python3-rpi.gpio,python-smbus,python3-smbus
      become: yes

   # din pacate Raspberry Pi Zero / unPi mini este prea incet
   - name: "Stergem Scratch 3 si Gcompris de pe unPi mini"
     apt:
       name: scratch3,gcompris
       state: absent
     become: yes
     
    - name: "Activam controlul serial al echipamentelor pe unPi mini"
      shell: raspi-config nonint do_i2c 0
      become: yes
      
    - name: "Instalam modulul Blinkt (cele 8 LED ale unPi mini)"
      apt:
        name: python-blinkt,python3-blinkt,realvnc-vnc-viewer
      become: yes

    - name: "Aducem un program exemplu pentru modulul Blinkt"
      uri:
        url: "https://raw.githubusercontent.com/pimoroni/blinkt/master/examples/random_blink_colours.py"
        status_code: [200,404]
        timeout: 10
        return_content: yes
      register: blink

    - copy:
        dest: ~/blink
        mode: u=rwx,g=,o=
        content: "{{ blink.content }}"
      when: blink.status == 200 and blink.content is defined
